app:
  title: Backstage Demo
  baseUrl: http://localhost:3000
  support:
    url: https://github.com/backstage/backstage/issues
    items:
      - title: Backstage Community
        icon: chat
        links:
          - url: https://backstage.io/docs/overview/support
            title: Support and community
      - title: Backstage News
        icon: docs
        links:
          - url: https://backstage.io/blog/
            title: Backstage Blog

organization:
  name: Backstage

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
    img-src:
      [
        "'self'",
        "data:",
        "https://backstage.io",
        "https://img.shields.io/",
        "https://api.dicebear.com/",
        "https://kroki.io/",
        "https://www.bestpractices.dev/",
        "https://api.securityscorecards.dev",
      ]
    frame-src: ["https://www.youtube.com"]
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"
  reading:
    allow:
      - host: demo.backstage.io
        paths:
          - /api/graphql/schema

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  gitlab:
    - host: localhost:8090
      token: glpat-ozkVtV66urRaFr5AzjtV
      baseUrl: http://localhost:8090/
      apiBaseUrl: http://localhost:8090/api/v4

auth:
  environment: development
  providers:
    guest:
      userEntityRef: user:default/guest
    github:
      development:
        clientId: ${GITHUB_DEVELOPMENT_CLIENT_ID}
        clientSecret: ${GITHUB_DEVELOPMENT_CLIENT_SECRET}

catalog:
  readonly: true
  rules:
    - allow: [Component, API, System, Domain, Resource, Location, User, Group]
  locations:

    # Backstage example systems
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

    # Backstage example organization groups
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml

    # The backstage demo deployment (this)
    - type: url
      target: https://github.com/backstage/demo/blob/master/catalog-info.yaml

    # Demo Software Template
    - type: file
      target: ../../catalog-info.yaml

    # Demo Software Template
    - type: file
      target: ../../examples/static-site/template.yaml
      rules:
        - allow: [Template]

  providers:
    backstage:
      enabled: false
      schedule:
        frequency: { hours: 12 }
        timeout: { minutes: 30 }

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers

techdocs:
  sanitizer:
    allowedIframeHosts:
      - www.youtube.com
  builder: "external"
  generator:
    runIn: "local"
  publisher:
    type: "local"

jenkins:
  baseUrl: http://localhost:8080
  headers:
    Authorization: Basic YmFja3N0YWdlOmJhY2tzdGFnZQ==

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: https://localhost:6443
          name: kind-backstage-cluster
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: true
          caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUFJNT3dkbno4T0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRFd01UUXhPREF4TlRCYUZ3MHpOREV3TVRJeE9EQTJOVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNpMnF6V1Rxa3ZBSzNGeVdSbTYvZC9MaVoxaWdBN0gxc0NLRUlFSy9lZ3BVcldyTGdEY3IxYVpSWS8KOXZuSjFHaEpObVpOdXhUZkJDTFFzL2dFTEw0aEszTEZ3eFZTdHpucGVmOFJTYzZVS0pVUURuSERJS1NKVnZMeQpZLzFVVFlkbEI1bHBHNXNJd2Y1WkVsUUJFWHRlVG1jRTFPVVdRY1AxNVkrQSsrV3dxVFVFbDlaQTF3UU44eGlOCk1HZTllZVRqRXBBZXRySnAwWTBtNGlyNEVOdFRYYWRvK1RoVjZ2bDZKMEZZWFMwYkxzVzBoVkVZaE1mY0xuYXUKOVIyalE0Zm0waFdWS0xibTZJanNLWS9jd0RsbGd5SUt5b28vdVZDL2lEOGl3YlRvOTN2S1llUllMYlQraytYNApxdExCUncwd0ppTnA4a2pWdko4TXNLVGNnVlg5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJReXpxU2ZQeHVCUEk5dENVaE5Ra0lWTW1NMUdqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUlGaHdSWXpoTgpna2preXJvUC9aOVkrT0MrRUQ1TFlreVgrSFg1WjVYeWQwdE1Qa2dLc0VnbGc0UzBlZFp5UWo2Zm5XWDVUSEZ4CnJReVliRUdYSDE3MUFvUmV2MGErbGFid1M3SFNxemJXYSt1L1hvZzRBLzhlTzF2bGJFUFlQQTdQQjdjUXZua3AKU2tGQWpkL0pKcXlYWDJUZVYrVVpuMkRZTUwzTWtsWmhTdGtlTUFFQlRDS2RHT2cvZjNTbzVWYi9LVEdYR2xXLwp1Z01NKzExbGJva3BXSjAvQzd4VXE5MS9zYkgvU0xPWncrZmR1ZUhtSmt0TGlvRGhHQzd0OHl5a01hSzl2R2poCkJTQ25oQjE2cnd3V1ZBMU92ajdKTElyNmpyZHY0ZTRYZG9wZStnT0RJZW5qVGtFWG9UNmlHTDk1OGM1Tyt1T1IKQ3ZQNzBmbXZhVmx6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IndiR2Q5YVE0RHJpUDV4UmNtOEVUVGRzTnRZWG1yMS1LNzEteFdzdEw1b3cifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImJhY2tzdGFnZS1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYmFja3N0YWdlLXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImY4OTQwNjVkLWM0NmYtNGFmYi05OGY2LWQyMWRhZWJlMWRjYSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmJhY2tzdGFnZS1zZXJ2aWNlLWFjY291bnQifQ.hz8i9ZjinnJn32ya6fc6q20Zp0hO9kfUgZ0WGyb3jCQRxJAJHPW-M2C6iF7OCPx1pYiB8pHw1BViC6Vpleq4cJMLrShJmmvOa4NX6gZ3PFXab6I0zYumPpYd3ZeTkqI9iKlV7PWT-ZDkr00ysCAKPZTGlIKAA2l3EEocObf5x8alCeWLtteBxxdzA0y8ceyWgIQMuO7DUR0m9ZiVCJ6qUSZmOwcHc6q1gZ-A4HWf_wMFZ0-vw1guKpgHR-XZWILwY2yJYkQnOa2E9HK-5SWahZzqIhE6_pZtofP6bwxhGz9I72EXvpi-kOGEQASdfKxRd13JcVLkJwYBAbA7JTNDpg

explore:
  tools:
    - title: "Tech Radar"
      description: "Tech Radar is a list of technologies, complemented by an assessment result, called ring assignment."
      url: "/tech-radar"
      image: "/tech-radar.png"
      tags: ["standards", "landscape"]
    - title: "Cost Insights"
      description: "Insights into cloud costs for your organization."
      url: "/cost-insights"
      image: "/google-cloud.png"
      tags: ["cloud", "finops"]
    - title: "GraphiQL"
      description: "Integrates GraphiQL as a tool to browse GraphiQL endpoints inside Backstage."
      url: "/graphiql"
      image: "/graphiql.png"
      tags: ["graphql", "dev"]

proxy:
  endpoints:
    "/jenkins/api":
      target: "http://localhost:8080"
      changeOrigin: true
      headers:
        Authorization: Basic YmFja3N0YWdlOmJhY2tzdGFnZQ==
