app:
  title: Backstage Demo
  baseUrl: http://backstage-local:3000
  experimental:
    # Auto discovering all plugins extensions
    packages: all
  extensions:
    # Enabling some entity cards
    # The cards will be displayed in the same order it appears in this setting list
    # Shows a table of components that provides a particular api
    - entity-card:api-docs/providing-components:
        config:
          # Presenting the card ony for entites of kind api
          filter: kind:component
    # Shows a table of components that consumes a particular api
    - entity-card:api-docs/consuming-components:
        config:
          # Presenting the card ony for entites of kind api
          filter: kind:component
    # Enabling some contents
    # The contents will be displayed in the same order it appears in this setting list
    # Shows a "Definition" tab for entities of kind api
    - entity-content:api-docs/definition:
        config:
          # A text-based query used to filter whether the entity contentextension should be rendered or not.
          # For more information about entity cards filters, check out this pull request
          # https://github.com/backstage/backstage/pull/21480
          # defaults to 'kind:component'
          filter: 'kind:component'
    # Shows an "Apis" tab for entities of kind component
    - entity-content:api-docs/apis:
        config:
          # A text-based query used to filter whether the entity contentextension should be rendered or not.
          # For more information about entity cards filters, check out this pull request
          # https://github.com/backstage/backstage/pull/21480
          # defaults to 'kind:component'
          filter: 'kind:component'
  support:
    url: https://github.com/backstage/backstage/issues
    items:
      - title: Backstage Community
        icon: chat
        links:
          - url: https://backstage.io/docs/overview/support
            title: Support and community
      - title: Backstage News
        icon: docs
        links:
          - url: https://backstage.io/blog/
            title: Backstage Blog

organization:
  name: Backstage

backend:
  baseUrl: http://backstage-local:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
    img-src:
      [
        "'self'",
        "data:",
        "https://backstage.io",
        "https://img.shields.io/",
        "https://api.dicebear.com/",
        "https://kroki.io/",
        "https://www.bestpractices.dev/",
        "https://api.securityscorecards.dev",
      ]
    frame-src: ["https://www.youtube.com"]
  cors:
    origin: http://backstage-local:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"
  reading:
    allow:
      - host: demo.backstage.io
        paths:
          - /api/graphql/schema

integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_API_KEY}
      baseUrl: ${GITLAB_URL}
      apiBaseUrl: ${GITLAB_API_BASE_URL}

auth:
  environment: development
  providers:
    guest:
      userEntityRef: user:default/guest
    gitlab:
      development:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        audience: ${GITLAB_URL}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

catalog:
  readonly: false
  rules:
    - allow: [Component, API, System, Domain, Resource, Location, User, Group, Template]
  processingInterval: { seconds: 30 }
  locations:
    # Users
    - name: backstage-demo-user
      type: file
      target: ./static/users/backstage-demo.yaml
    # Groups
    - name: backstage-demo-group
      type: file
      target: ./static/groups/backstage-demo.yaml

    # Backstage example systems
    - type: url
      target: ${GITLAB_URL}/backstage-demo/templates/hello-world-app/-/blob/main/template.yaml
    - type: url
      target: ${GITLAB_URL}/backstage-demo/templates/hello-world-service/-/blob/main/template.yaml

  providers:
    gitlab:
      gitlab:
        host: ${GITLAB_HOST}
        branch: main
        fallbackBranch: master
        skipForkedRepos: false
        # group: backstage-demo
        orgEnabled: true
        group: backstage-demo
        restrictUsersToGroup: false
        includeUsersWithoutSeat: true
        excludeRepos: []
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 3 }
    backstage:
      enabled: false
      schedule:
        frequency: { hours: 12 }
        timeout: { minutes: 30 }

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers

techdocs:
  sanitizer:
    allowedIframeHosts:
      - www.youtube.com
  builder: "external"
  generator:
    runIn: "local"
  publisher:
    type: "local"

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: ${KUBERNETES_API_BASE_URL}
          name: ${KUBERNETES_CLUSTER_NAME}
          authProvider: serviceAccount
          skipTLSVerify: ${KUBERNETES_SKIP_TLS}
          skipMetricsLookup: ${KUBERNETES_SKIP_METRICS}
          caData: ${KUBERNETES_CLIENT_CERTIFICATE_DATA}
          serviceAccountToken: ${KUBERNETES_CLIENT_KEY_DATA}

explore:
  tools:
    - title: "Tech Radar"
      description: "Tech Radar is a list of technologies, complemented by an assessment result, called ring assignment."
      url: "/tech-radar"
      image: "/tech-radar.png"
      tags: ["standards", "landscape"]
    - title: "Cost Insights"
      description: "Insights into cloud costs for your organization."
      url: "/cost-insights"
      image: "/google-cloud.png"
      tags: ["cloud", "finops"]
    - title: "GraphiQL"
      description: "Integrates GraphiQL as a tool to browse GraphiQL endpoints inside Backstage."
      url: "/graphiql"
      image: "/graphiql.png"
      tags: ["graphql", "dev"]

proxy:
  '/argocd/api':
    target: ${ARGOCD_BASE_URL}/api/v1/
    changeOrigin: true
    secure: false
    headers:
      Authorization: 'Bearer ${ARGOCD_TOKEN}'

argocd:
  baseUrl: ${ARGOCD_BASE_URL}