app:
  title: Backstage Demo
  baseUrl: http://localhost:3000
  support:
    url: https://github.com/backstage/backstage/issues
    items:
      - title: Backstage Community
        icon: chat
        links:
          - url: https://backstage.io/docs/overview/support
            title: Support and community
      - title: Backstage News
        icon: docs
        links:
          - url: https://backstage.io/blog/
            title: Backstage Blog

organization:
  name: Backstage

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
    img-src:
      [
        "'self'",
        "data:",
        "https://backstage.io",
        "https://img.shields.io/",
        "https://api.dicebear.com/",
        "https://kroki.io/",
        "https://www.bestpractices.dev/",
        "https://api.securityscorecards.dev",
      ]
    frame-src: ["https://www.youtube.com"]
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"
  reading:
    allow:
      - host: demo.backstage.io
        paths:
          - /api/graphql/schema

integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      baseUrl: ${GITLAB_BASE_URL}
      apiBaseUrl: ${GITLAB_API_BASE_URL}

auth:
  environment: development
  providers:
    guest:
      userEntityRef: user:default/guest
    gitlab:
      development:
        clientId: ${GITLAB_DEVELOPMENT_CLIENT_ID}
        clientSecret: ${GITLAB_DEVELOPMENT_CLIENT_SECRET}
        audience: http://localhost:8090
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

catalog:
  readonly: true
  rules:
    - allow: [Component, API, System, Domain, Resource, Location, User, Group]
  locations:
    # Backstage example systems
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all-systems.yaml

    # Backstage example organization groups
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml

    # The backstage demo deployment (this)
    - type: url
      target: https://github.com/backstage/demo/blob/master/catalog-info.yaml

    # Demo Software Template
    - type: file
      target: ../../catalog-info.yaml

    # Demo Software Template
    - name: static-site
      type: file
      target: ../../examples/static-site/template.yaml
      rules:
        - allow: [Template]
    - name: java-app
      type: file
      target: ../../examples/java-app/template.yaml
      rules:
        - allow: [Template]

  providers:
    gitlab:
      gitlab:
        host: ${GITLAB_HOST}
        branch: main
        fallbackBranch: master
        skipForkedRepos: false
        # group: backstage-demo
        orgEnabled: true
        group: backstage-demo
        restrictUsersToGroup: false
        includeUsersWithoutSeat: true
        excludeRepos: []
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 3 }
    backstage:
      enabled: false
      schedule:
        frequency: { hours: 12 }
        timeout: { minutes: 30 }

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers

techdocs:
  sanitizer:
    allowedIframeHosts:
      - www.youtube.com
  builder: "external"
  generator:
    runIn: "local"
  publisher:
    type: "local"

jenkins:
  baseUrl: ${JENKINS_BASE_URL}
  username: ${JENKINS_USERNAME}
  password: ${JENKINS_PASSWORD}
  crumbIssuerEnabled: ${JENKINS_CRUMB_ISSUER_ENABLED}

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: ${KUBERNETES_API_BASE_URL}
          name: ${KUBERNETES_CLUSTER_NAME}
          authProvider: serviceAccount
          skipTLSVerify: ${KUBERNETES_SKIP_TLS}
          skipMetricsLookup: ${KUBERNETES_SKIP_METRICS}
          caData: ${KUBERNETES_CLIENT_CERTIFICATE_DATA}
          serviceAccountToken: ${KUBERNETES_CLIENT_KEY_DATA}

explore:
  tools:
    - title: "Tech Radar"
      description: "Tech Radar is a list of technologies, complemented by an assessment result, called ring assignment."
      url: "/tech-radar"
      image: "/tech-radar.png"
      tags: ["standards", "landscape"]
    - title: "Cost Insights"
      description: "Insights into cloud costs for your organization."
      url: "/cost-insights"
      image: "/google-cloud.png"
      tags: ["cloud", "finops"]
    - title: "GraphiQL"
      description: "Integrates GraphiQL as a tool to browse GraphiQL endpoints inside Backstage."
      url: "/graphiql"
      image: "/graphiql.png"
      tags: ["graphql", "dev"]

proxy:
  endpoints:
    "/jenkins/api":
      target: ${JENKINS_BASE_URL}
      changeOrigin: true
      headers:
        Authorization: ${JENKINS_AUTHORIZATION}
