apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup-jenkins-test
  description: Artist Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    backstage.io/source-template: template:default/springboot-template
    backstage.io/linguist: "https://github.com/backstage/backstage/tree/master/plugins/playlist"
    backstage.io/kubernetes-label-selector: 'app=foo'
    jenkins.io/job-full-name: 'backstage-demo/static-site-pipeline'
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/backstage-demo"

