image: docker:latest

services:
    docker:dind

stages:
    build

variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/static-site-pipeline"  # Define the image name based on your GitLab project registry URL
    DOCKER_TAG: "main-$CI_COMMIT_SHORT_SHA"

build_and_push_image:
    stage: build
        script:
        - echo "Building Docker image..."
        - docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" .
        - echo "Pushing Docker image to GitLab Container Registry..."
        - docker push "$DOCKER_IMAGE:$DOCKER_TAG"
        only:
            main  # Run this job only on the main branch
        before_script:
            docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
