apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id | dump }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/${{values.owner}}
  definition:
    $text: ./api-docs.json