apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump }}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.owner + "/" + values.repo}}
    backstage.io/kubernetes-label-selector: 'app=${{values.component_id}}'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:default/${{values.owner}}
  providesApis:
    - ${{values.component_id}}
