apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}-service
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ${{ values.component_id }}