# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: static-site-pipeline-template
  title: Static Site Pipeline Template
  description: |
    This template will create a simple static site app repository under owner folder/group and a related job jenkins with under the same folder.
    You will obtain button links after job execution
spec:
  type: website
  parameters:
    - title: Choose a location
      description: |
        This section will ask for details about the Owner and Repository name which will then be used
        to create a repository in that location using your GitHub credentials.
      properties:
        jenksinsFileContent:
          title: Jenkins File Content
          type: string
          description: Jenkins file content will be created and attached to repository
          ui:autofocus: true
          ui:widget: textarea
          ui:options:
            rows: 20
          default: |
            pipeline {
              agent any
              environment {
                  REGISTRY_URL = 'http://gitlab.local:5050'
                  IMAGE_NAME = 'gitlab.local:5050/backstage-demo/static-site-pipeline:latest'
              }
              stages {
                stage('Docker version') {
                  steps {
                    echo "Printing docker version"
                    sh 'docker version'
                  }
                }
                stage('Docker login') {
                  steps {
                    withCredentials([usernamePassword(credentialsId: 'gitlab-credentials', usernameVariable: 'GITLAB_USER', passwordVariable: 'GITLAB_TOKEN')]) {
                      sh ('echo ${GITLAB_TOKEN} | docker login -u ${GITLAB_USER} --password-stdin ${REGISTRY_URL}')
                    }
                  }
                }
                stage('Build') {
                  steps {
                    echo "Building app"
                    sh('docker build -t ${IMAGE_NAME} .')
                  }
                }
                stage('Publish') {
                  steps {
                    echo "Publishing image"
                    sh ('docker push ${IMAGE_NAME}')
                  }
                }
                stage('Docker logout') {
                  steps {
                    echo "Logout from registry url ${REGISTRY_URL}"
                    sh ('docker logout ${REGISTRY_URL}')
                  }
                }
              }
            }
        jenksinsFilePath:
          title: Jenkins File Path
          type: string
          description: Jenkins file path
          default: ./Jenkinsfile
        jenkinsGitlabCredentials:
          title: Jenkins Gitlab Credentials Id
          type: string
          description: Jenkins credentials id configured on jenkins instance
          default: gitlab-credentials
        repoUrl:
          title: Enter an Owner and Repository Name
          description: |
            The Owner should be your GitHub username. The Repository name should be a name that is not one that exists already in your GitHub account.
          type: string
          ui:autofocus: true
          ui:field: RepoUrlPicker
          default: gitlab.local:8090?owner=backstage-demo&repo=static-site-pipeline
          ui:options:
            allowedHosts:
              - gitlab.local:8090
  steps:
    - id: list-inputs
      name: List Inputs
      action: debug:log
      input:
        message: |
          The following inputs were pre-selected:
            - Repo URL: ${{ parameters.repoUrl }}
            - Owner: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
            - Repo: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
    - id: writeFile
      name: Create File
      action: roadiehq:utils:fs:write
      input:
        path: ${{ parameters.jenksinsFilePath }}
        content: ${{ parameters.jenksinsFileContent }}
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./content
        values:
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ["gitlab.local:8090"]
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        defaultBranch: main
        description: Repository Created by Demo template
    - id: jenkins-job-create
      name: Jenkins Job Create
      action: jenkins:job:create
      input:
        jobName: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        jobType: pipeline
        repoUrl: http://gitlab:8090/${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}.git
        gitlabCredentials: ${{ parameters.jenkinsGitlabCredentials }}
        description: Jenkins job creation
    - id: jenkins-job-build
      name: Jenkins Job Build
      action: jenkins:job:build
      input:
        jobName: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        description: Jenkins job run
  output:
    links:
      - url: http://gitlab.local:8090/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        title: "Gitlab Repository"
      - url: http://jenkins.local:8080/job/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/job/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        title: "Jenkins Job"
