# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: static-site-template
  title: Static Site Template
  description: |
    This template will create a static site repository under owner folder/group and a related job jenkins with under the same folder.
    You will obtain button links after job execution
spec:
  type: website
  parameters:
    - title: Choose a location
      description: |
        This section will ask for details about the Owner and Repository name which will then be used
        to create a repository in that location using your GitHub credentials.
      properties:
        repoUrl:
          title: Enter an Owner and Repository Name
          description: |
            The Owner should be your GitHub username. The Repository name should be a name that is not one that exists already in your GitHub account.
          type: string
          ui:autofocus: true
          ui:field: RepoUrlPicker
          default: gitlab-local?owner=backstage-demo&repo=static-site
          ui:options:
            allowedHosts:
              - gitlab-local
  steps:
    - id: list-inputs
      name: List Inputs
      action: debug:log
      input:
        message: |
          The following inputs were pre-selected:
            - Repo URL: ${{ parameters.repoUrl }}
            - Owner: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
            - Repo: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./content
        values:
          component_id: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          description: 'Static site component'
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ["gitlab-local"]
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        defaultBranch: main
    - id: jenkins-job-create
      name: Jenkins Job Create
      action: jenkins:job:create
      input:
        jobName: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
        jobXml: |
          <flow-definition plugin="workflow-job@1447.v559b_c710cd2e">
            <actions/>
            <description></description>
            <keepDependencies>false</keepDependencies>
            <properties>
                <com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.9.4">
                    <gitLabConnection>gitlab</gitLabConnection>
                    <jobCredentialId></jobCredentialId>
                    <useAlternativeCredential>false</useAlternativeCredential>
                </com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
            </properties>
            <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@3975.v567e2a_1ffa_22">
                <scm class="hudson.plugins.git.GitSCM" plugin="git@5.6.0">
                    <configVersion>2</configVersion>
                    <userRemoteConfigs>
                        <hudson.plugins.git.UserRemoteConfig>
                            <url>${{ steps.publish.output.remoteUrl }}</url>
                            <credentialsId>gitlab-credentials</credentialsId>
                        </hudson.plugins.git.UserRemoteConfig>
                    </userRemoteConfigs>
                    <branches>
                        <hudson.plugins.git.BranchSpec>
                          <name>*/main</name>
                        </hudson.plugins.git.BranchSpec>
                    </branches>
                    <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
                    <submoduleCfg class="empty-list"/>
                    <extensions/>
                </scm>
                <scriptPath>Jenkinsfile</scriptPath>
                <lightweight>true</lightweight>
            </definition>
            <triggers/>
            <disabled>false</disabled>
          </flow-definition>
    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
  output:
    links:
      - url: ${{ steps.publish.output.repoContentsUrl }}
        title: "Gitlab Repository"
      - url: http://jenkins-local:8080/job/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/job/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
        title: "Jenkins Job"
