# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-app-template
  title: Java App Template
  description: |
    This template will create a simple java app repository under owner folder/group and a related job jenkins with under the same folder.
    You will obtain button links after job execution
spec:
  type: website
  parameters:
    - title: Choose a location
      description: |
        This section will ask for details about the Owner and Repository name which will then be used
        to create a repository in that location using your GitHub credentials.
      properties:
        jenksinsFileContent:
          title: Jenkins File Content
          type: string
          description: Jenkins file content will be created and attached to repository
          ui:autofocus: true
          ui:widget: textarea
          ui:options:
            rows: 20
          default: |
            pipeline {
              agent any
              stages {
                stage('Build') {
                  steps {
                    echo "building"
                    sleep 10
                  }
                }
                stage('Test') {
                  steps {
                    echo "testing"
                    sleep 30
                  }
                }
                stage('Deploy') {
                  steps {
                    echo "deploying"
                    stageMessage "sample stage message"
                  }
                }
              }
            }
        jenksinsFilePath:
          title: Jenkins File Path
          type: string
          description: Jenkins file path
          default: ./Jenkinsfile
        repoUrl:
          title: Enter an Owner and Repository Name
          description: |
            The Owner should be your GitHub username. The Repository name should be a name that is not one that exists already in your GitHub account.
          type: string
          ui:autofocus: true
          ui:field: RepoUrlPicker
          default: localhost:8090?owner=backstage-test&repo=java-app
          ui:options:
            allowedHosts:
              - localhost:8090
  steps:
    - id: list-inputs
      name: List Inputs
      action: debug:log
      input:
        message: |
          The following inputs were pre-selected:
            - Repo URL: ${{ parameters.repoUrl }}
            - Owner: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
            - Repo: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
    - id: writeFile
      name: Create File
      action: roadiehq:utils:fs:write
      input:
        path: ${{ parameters.jenksinsFilePath }}
        content: ${{ parameters.jenksinsFileContent }}
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./content
        values:
          owner: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ["localhost:8090"]
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        defaultBranch: main
        description: Repository Created by Demo template
    - id: jenkins-job-create
      name: Jenkins Job Create
      action: jenkins:job:create
      input:
        jobName: ${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        jobType: pipeline
        repoUrl: http://gitlab:8090/${{ (parameters.repoUrl | parseRepoUrl).owner }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}.git
        description: Jenkins job creation
  output:
    links:
      - url: http://localhost:8090/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        title: "Github Repository"
      - url: http://localhost:8080/job/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/job/${{ (parameters.repoUrl | parseRepoUrl).repo }}
        title: "Jenkins Job"
