image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/${{ values.component_id }}"
    DOCKER_TAG: "latest"

stages:
    - build
    - deploy

docker:
    stage: build
    script:
        - echo "Building Docker image..."
        - docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" .
        - docker tag "$DOCKER_IMAGE:$DOCKER_TAG" "ttl.sh/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$DOCKER_TAG"
        - echo "Pushing Docker image to GitLab Container Registry..."
        - docker push "$DOCKER_IMAGE:$DOCKER_TAG"
        - docker push "ttl.sh/$CI_PROJECT_PATH/$CI_PROJECT_NAME:$DOCKER_TAG"
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    after_script:
        - docker logout "$CI_REGISTRY"

argo:
    stage: deploy
    image: argoproj/argocd:v2.6.15
    script:
        - echo "Creating ArgoCD Application..."
        - argocd login argocd-local:7443 --insecure --grpc-web --username admin --password Qb8jHP1rU74LFfLZ
        - argocd repo add "http://172.17.0.1/$CI_PROJECT_PATH.git" --project default --username root --password -rob123-
        - argocd app create ${{ values.component_id }} --upsert --repo "http://172.17.0.1/$CI_PROJECT_PATH.git" --path gitops/overlays --dest-namespace default --dest-server https://kubernetes.default.svc
        - argocd app sync ${{ values.component_id }}
        - argocd app wait ${{ values.component_id }}

