image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/${{ values.component_id }}"
    DOCKER_TAG: "main-$CI_COMMIT_SHORT_SHA"

stages:
    - build

docker-build:
    stage: build
    script:
        - echo "Building Docker image..."
        - docker build -t "$DOCKER_IMAGE:$DOCKER_TAG" .
        - echo "Pushing Docker image to GitLab Container Registry..."
        - docker push "$DOCKER_IMAGE:$DOCKER_TAG"
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"