services:

  gitlab:
    image: gitlab/gitlab-ce:17.5.0-ce.0
    container_name: gitlab
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8090'

        letsencrypt['enable'] = false

        gitlab_rails['gitlab_default_can_create_group'] = true
        gitlab_rails['gitlab_default_projects_features_visibility_level'] = 20
        gitlab_rails['gitlab_email_confirmation_enabled'] = false
        gitlab_rails['gitlab_email_confirmation'] = false
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
        gitlab_rails['gitlab_signup_enabled'] = true
        gitlab_rails['gitlab_user_create_password_set_when_invited'] = true
        gitlab_rails['gitlab_username_changing_enabled'] = true
        gitlab_rails['sign_in_after_signup'] = true
        gitlab_rails['user_default_internal_regex'] = nil
        gitlab_rails['user_is_active'] = true
        gitlab_rails['user_show_secondary_emails'] = false

        registry_external_url 'http://localhost:5050'

        gitlab_rails['registry_enabled'] = true
        gitlab_rails['registry_host'] = "localhost"
        gitlab_rails['registry_port'] = "5050"
        gitlab_rails['registry_path'] = "/opt/gitlab/etc/registry/storage"

        nginx['listen_port'] = 8090
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false

        # registry['enable'] = true
        # registry['registry_http_addr'] = "localhost:5050"
        # registry['env_directory'] = "/opt/gitlab/etc/registry/env"
        # registry['log_directory'] = "/var/log/gitlab/registry"
        # registry_nginx['redirect_http_to_https'] = false

      GITLAB_ROOT_PASSWORD: '-rob123-'
    ports:
      - "8090:8090"
      - "8443:443"
      - "5050:5050"
      - "2424:2424"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_container_storage:/opt/gitlab/etc/registry/storage

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker in Jenkins
    depends_on:
      - gitlab

volumes:
  gitlab_config:
  gitlab_container_storage:
  gitlab_data:
  gitlab_logs:
  jenkins_home: